-- Table: LoaiSP
CREATE TABLE LoaiSP (
    MaLoaiSP NVARCHAR(10) PRIMARY KEY,
    TenLoai NVARCHAR(50) NOT NULL
);

-- Table: NhaCungCap
CREATE TABLE NhaCungCap (
    MaNhaCC NVARCHAR(10) PRIMARY KEY,
    TenNhaCC NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50),
    SDT NVARCHAR(12)
);

-- Table: ChatLieuSP
CREATE TABLE ChatLieuSP (
    MaChatLieu NVARCHAR(10) PRIMARY KEY,
    ChatLieu NVARCHAR(50) NOT NULL
);

-- Table: KhachHang
CREATE TABLE KhachHang (
    MaKH NVARCHAR(10) PRIMARY KEY,
    Ho NVARCHAR(50),
    Ten NVARCHAR(50) NOT NULL,
    SDTChinh NVARCHAR(12) UNIQUE NOT NULL,
    EmailChinh NVARCHAR(50) UNIQUE NOT NULL
);

-- Table: NhanVien
CREATE TABLE NhanVien (
    MaNV NVARCHAR(10) PRIMARY KEY,
    Ho NVARCHAR(50),
    Ten NVARCHAR(50) NOT NULL,
    Email NVARCHAR(50) UNIQUE NOT NULL,
    SDT NVARCHAR(12) UNIQUE NOT NULL,
    ChucVu NVARCHAR(50) NOT NULL
);

-- Table: DonHang
CREATE TABLE DonHang (
    MaDH NVARCHAR(10) PRIMARY KEY,
    NgayMua DATE NOT NULL,
    TrangThai NVARCHAR(50),
    MaKH NVARCHAR(10),
    MaNV NVARCHAR(10),
    TongTien DECIMAL(10,2) NOT NULL,
    PhuongThucTT NVARCHAR(50),
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
);

-- Table: SanPham
CREATE TABLE SanPham (
    MaSP NVARCHAR(10) PRIMARY KEY,
    Ten NVARCHAR(50) NOT NULL,
    GiaHienTai DECIMAL(10,2) NOT NULL,
    SoLuongTon INT NOT NULL,
    MaLoaiSP NVARCHAR(10),
    MaNhaCC NVARCHAR(10),
    MauSac NVARCHAR(50),
    MaChatLieu NVARCHAR(10),
    Size NVARCHAR(10),
    FOREIGN KEY (MaLoaiSP) REFERENCES LoaiSP(MaLoaiSP) ON DELETE CASCADE,
    FOREIGN KEY (MaNhaCC) REFERENCES NhaCungCap(MaNhaCC) ON DELETE CASCADE,
    FOREIGN KEY (MaChatLieu) REFERENCES ChatLieuSP(MaChatLieu) ON DELETE CASCADE
);

-- Table: KhuyenMai
CREATE TABLE KhuyenMai (
    MaKM NVARCHAR(10) PRIMARY KEY,
    TenKM NVARCHAR(50) NOT NULL,
    KieuKM NVARCHAR(50),
    NgayBatDau DATE NOT NULL,
    NgayKetThuc DATE NOT NULL
);

-- Table: CTKMVC (ChiTietKMVC)
CREATE TABLE CTKMVC (
    MaSP NVARCHAR(10),
    MaKM NVARCHAR(10),
    TienGiam DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (MaSP, MaKM),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM) ON DELETE CASCADE
);

-- Table: CTKMP (ChiTietKMP)
CREATE TABLE CTKMP (
    MaSP NVARCHAR(10),
    MaKM NVARCHAR(10),
    TienGiam DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (MaSP, MaKM),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM) ON DELETE CASCADE
);

-- Table: CTDonHang
CREATE TABLE CTDonHang (
    MaDH NVARCHAR(10),
    MaSP NVARCHAR(10),
    MaKM NVARCHAR(10),
    GiaBan DECIMAL(10,2) NOT NULL,
    SoLuong INT NOT NULL,
    PRIMARY KEY (MaDH, MaSP),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH) ON DELETE CASCADE,
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE,
    FOREIGN KEY (MaKM) REFERENCES KhuyenMai(MaKM) ON DELETE CASCADE
);

-- Table: Log
CREATE TABLE Log (
    LogID INT PRIMARY KEY IDENTITY(1,1),
    HanhDong NVARCHAR(255) NOT NULL,
    MaNV NVARCHAR(10),
    Ngay DATE NOT NULL,
    FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE
);

-- Insert sample data into NhanVien
INSERT INTO NhanVien (MaNV, Ho, Ten, ChucVu, Email, SDT)
VALUES (N'001', N'Nguyễn', N'Văn A', N'Nhân Viên', N'nguyenvana@gmail.com', N'0123456789');
